package org.graphstream.algorithm.community;

public enum MobileMarker {
X, Y, WEIGHT, MODULE, COMMUNITY, COMMUNITY_SCORE, COMMUNITY2, COMMUNITY_SCORE2, SPEED, AVG_SPEED, LANE, ANGLE, SLOPE, POS, DISTANCE, DSD, IDSD, CONGESTION, DYNAMISM, TIMEMEANSPEED,
}